spring:
  datasource:
    url: jdbc:postgresql://${LEGACY_PG_HOST:localhost}:${LEGACY_PG_PORT:5432}/${LEGACY_PG_DB:legacydb}
    username: ${LEGACY_PG_USER:postgres}
    password: ${LEGACY_PG_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      initialization-fail-timeout: -1

app:
  jwt:
    secret: ${JWT_SECRET:change-me}
    issuer: ${JWT_ISSUER:banking-modernization}
    ttl-seconds: ${JWT_TTL_SECONDS:3600}
