/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.ErrorResponse;
import org.openapitools.model.LoginRequest;
import org.openapitools.model.LoginResponse;
import org.openapitools.model.TransferRequest;
import org.openapitools.model.TransferResponse;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-02-22T04:29:49.650640493Z[Etc/UTC]", comments = "Generator version: 7.6.0")
@Validated
public interface DefaultApi {

    /**
     * POST /auth/login : Authenticate a user and return a JWT
     *
     * @param loginRequest  (required)
     * @return Authentication successful (status code 200)
     *         or Authentication failed (status code 401)
     *         or Request validation failed (status code 400)
     *         or Unexpected server error (status code 500)
     */
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/auth/login",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<LoginResponse> login(
         @Valid @RequestBody LoginRequest loginRequest
    );


    /**
     * POST /accounts/{accountId}/transfer : Transfer funds from one account to another
     *
     * @param accountId Source account identifier (required)
     * @param transferRequest  (required)
     * @return Transfer processed (status code 200)
     *         or Transfer request invalid (status code 400)
     *         or Missing or invalid authentication (status code 401)
     *         or Unexpected server error (status code 500)
     */
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/accounts/{accountId}/transfer",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<TransferResponse> transferFunds(
        @Size(min = 1, max = 64)  @PathVariable("accountId") String accountId,
         @Valid @RequestBody TransferRequest transferRequest
    );

}
